name: Spacelift

on: [push]

jobs:
  test:
    name: Spacelift
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Generate token
        run: |
          OIDC_TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=halcyon.app.spacelift.io" | jq --raw-output '.value')
          echo "OIDC_TOKEN=$OIDC_TOKEN" >> $GITHUB_ENV

      - name: Install spacectl
        uses: spacelift-io/setup-spacectl@main

      - name: List modules
        env:
          SPACELIFT_API_KEY_ENDPOINT: "https://halcyon.app.spacelift.io"
          SPACELIFT_API_KEY_ID: "${{ secrets.SPACELIFT_API_KEY_ID }}"
          SPACELIFT_API_KEY_SECRET: "${{ secrets.SPACELIFT_API_KEY_SECRET }}"
        run: |
          spacectl whoami
          spacectl module list
